doc/Deploy_Manual.txt.4HiKey
doc/Grub_Manual.txt.4All
doc/Readme.txt.4HiKey
doc/Setup_HiKey_WiFi_Env.txt.4HiKey

estuary: doc : add HiKey document

---

build.sh

build: fix this HiKey git reset point for uefi

---

doc/Deploy_Manual.txt.4HiKey

doc: fix this detail bug for HiKey document

---

doc/Deploy_Manual.txt.4HiKey

DOC: fix bug which will support all SD card and tar order

---

doc/Deploy_Manual.txt.4D02
doc/Grub_Manual.txt.4All

doc: fix d02 grub.cfg and deploy txt to slove mac address

---

build.sh

Add prompt message for deprecated parameter.

---

doc/Deploy_Manual.txt.4HiKey

doc: fix HiKey deploy detail error

---

doc/Deploy_Manual.txt.4D02
doc/Deploy_Manual.txt.4HiKey

doc: reboot this D02 board after downloading DTB

---

build.sh

Modify prompt message for deprecated parameter in build.sh

---

build.sh

E.g.: Estuary version is v2.2.0.
Estuary version is the latest.

Add parameter -v and --version to print the current estuary version.

---

doc/Deploy_Manual.txt.4D02

doc: fix D02 deploy manual

---

create-udisk.sh
doc/Setup_PXE_Env_on_Host.txt.4All
find_disk.sh

fix the error of Setup_PXE_Env_on_Host.txt.4All

fix the error of Setup_PXE_Env_on_Host.txt.4All

---

common.sh

limit platform type to USB deployment

limit platform type to USB deployment

---

build.sh
changelist.txt
checksum/Debian_ARM64.tar.gz.sum
checksum/Fedora_ARM64.tar.gz.sum
checksum/OpenSuse_ARM64.tar.gz.sum
checksum/Ubuntu_ARM64.tar.gz.sum
default.xml

Modify distro path to cleandistro/pre_release/linux/v2.1/rc1/. Update estuary/checksum/.
Delete distro path for China.

Modify distro download path.

---

build.sh

Use regular expression to get distro postfix.

---

build.sh

Modify supported distros and related usage.

---

build.sh

Modify version information.

---

default.xml

Delete all tags in default.xml.

---

build.sh
checksum/binaries.sum
default.xml

Fix prebuilt binaries path for HiKey.
Fix syntax error for rc.local.

Fix bugs for HiKey and rc.local.

---

README

Update version.
Update referred website addresses.

Update README for version 2.1.

---

default.xml

Modify ref tags.

---

default.xml

Delete revision in default.xml.

---

build.sh

Add aarch64 native build related process.
Change http://open-estuary.com to http://open-estuary.org.

Add native build related process.

---

build.sh

Delete iasl update condition.
Delete uefi commit id.

build.sh: Modify UEFI related scripts

---

doc/Deploy_Manual.txt.4D02

doc: acpi: add acpi using way for D02

---

doc/Armor_Manual.txt.4All
doc/Armor_Tools_Basic_Info.txt.4All
doc/Armor_Tools_Supported.txt.4All
doc/README.armor.iptables
doc/README.armor.kgdb.kdb
doc/README.armor.lttng
doc/README.armor.perf

Committed consolidated Armor documents to estuary/doc.

Armor documents

---

doc/Grub_Manual.txt.4All

d02: grub: fix this bug about mac address

---

doc/Armor_Tools_Supported.txt.4All
post_install.sh

Committed changes for Armor tools support on Debian.

Changes for Armor tools support on Debian

---

doc/Deploy_Manual.txt.4D02

Add ESL boot mode and its instruction.
Add other boot mode's instructions.

Add instructions for each boot mode.

---

doc/Deploy_Manual.txt.4D02
doc/Grub_Manual.txt.4All

MAC address duplicate issue.
I have also corrected some incorrect comment in grub.cfg sample
and some minor spelling and formating errors.
Signed-off-by: Anurup M <anurup.m@huawei.com>

d02: doc: Update documentation adding notes for the known

---

build.sh
checksum/CentOS_ARM64.tar.gz.sum
checksum/Debian_ARM64.tar.gz.sum
checksum/Fedora_ARM64.tar.gz.sum
checksum/OpenSuse_ARM64.tar.gz.sum
checksum/Ubuntu_ARM32.tar.gz.sum
checksum/Ubuntu_ARM64.tar.gz.sum
checksum/binaries.sum
estuarycfg.json
mkisoimg.sh
mkusbinstall.sh
setup.sh

1. UEFI update for D02, D03, HiKey.
2. prebuild, distro patch change to v2.2rc0.
3. OpenSuse rc.local change to after.local.
4. Integrate iso/usb install feature for v2.2rc0
5. Delete package build check.

Change for v2.2rc0

---

doc/README.armor.perf

Updated the README based on the RAW event encoding format to add CPU DIE ID, Module ID etc.
Signed-off-by: Anurup M <anurup.m@huawei.com>

d02: doc: Perf - Update README based on the latest RAW event encoding

---

doc/Deploy_Manual.txt.4D03

Signed-off-by: tianjiaoling <tianjiaoling@126.com>

d03: doc: delete norflash boot for deploy

---

doc/Armor_Tools_Basic_Info.txt.4All
doc/Armor_Tools_Supported.txt.4All
doc/README.armor.perf

Update perf doc adding information on DDRC event counters and some known issues in the current solution
Signed-off-by: Anurup M <anurup.m@huawei.com>

d02: doc: Perf - Add DDRC event counting example and Known Issues

---

build.sh
checksum/binaries.sum
estuarycfg.json
mkisoimg.sh
mkusbinstall.sh
setup.sh

Update iso/usb install scripts for D02/D03.

---

doc/Armor_Manual.txt.4All
doc/Armor_Tools_Supported.txt.4All

Updated Armor documents for CentOS.

Updated Armor documents for CentOS

---

build.sh

Update HiKey UEFI build command.
